// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Contact struct {
	ZohoID       string
	FirstName    string
	LastName     string
	Organization string
	Email        string
	Phone        string
	Mobile       string
	Street       string
	City         string
	PostalCode   string
	Status       string
	ModifiedTime time.Time
	Raw          json.RawMessage
	SyncedAt     time.Time
}

type Token struct {
	ID        uuid.UUID
	UserSub   string
	Name      string
	ExpiresAt sql.NullTime
	CreatedAt time.Time
}

type UserOfflineToken struct {
	UserSub      string
	OfflineToken []byte
	UpdatedAt    time.Time
}
