// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: queries.sql

package database

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const allContacts = `-- name: AllContacts :many
SELECT zoho_id, first_name, last_name, organization, email, phone, mobile, street, city, postal_code, status, modified_time, raw, synced_at FROM contacts ORDER BY last_name, first_name
`

func (q *Queries) AllContacts(ctx context.Context) ([]Contact, error) {
	rows, err := q.db.QueryContext(ctx, allContacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ZohoID,
			&i.FirstName,
			&i.LastName,
			&i.Organization,
			&i.Email,
			&i.Phone,
			&i.Mobile,
			&i.Street,
			&i.City,
			&i.PostalCode,
			&i.Status,
			&i.ModifiedTime,
			&i.Raw,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createTokenForUser = `-- name: CreateTokenForUser :one
INSERT INTO tokens (user_sub, token_hash) VALUES ($1, $2) RETURNING id, created_at
`

type CreateTokenForUserParams struct {
	UserSub   string
	TokenHash []byte
}

type CreateTokenForUserRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) CreateTokenForUser(ctx context.Context, arg CreateTokenForUserParams) (CreateTokenForUserRow, error) {
	row := q.db.QueryRowContext(ctx, createTokenForUser, arg.UserSub, arg.TokenHash)
	var i CreateTokenForUserRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteContactsSyncedBefore = `-- name: DeleteContactsSyncedBefore :execrows
DELETE FROM contacts WHERE synced_at < $1
`

func (q *Queries) DeleteContactsSyncedBefore(ctx context.Context, syncedAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteContactsSyncedBefore, syncedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteLongExpiredTokens = `-- name: DeleteLongExpiredTokens :execrows
DELETE FROM tokens WHERE expires_at < now() - interval '1 year'
`

func (q *Queries) DeleteLongExpiredTokens(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLongExpiredTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOfflineTokensForUserSubs = `-- name: DeleteOfflineTokensForUserSubs :execrows
DELETE FROM user_offline_tokens WHERE user_sub = ANY($1::text[])
`

func (q *Queries) DeleteOfflineTokensForUserSubs(ctx context.Context, dollar_1 []string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOfflineTokensForUserSubs, pq.Array(dollar_1))
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTokenForUser = `-- name: DeleteTokenForUser :execrows
DELETE FROM tokens WHERE id = $1 AND user_sub = $2
`

type DeleteTokenForUserParams struct {
	ID      uuid.UUID
	UserSub string
}

func (q *Queries) DeleteTokenForUser(ctx context.Context, arg DeleteTokenForUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTokenForUser, arg.ID, arg.UserSub)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const expireTokensForUserSubs = `-- name: ExpireTokensForUserSubs :execrows
UPDATE tokens SET expires_at = now() WHERE user_sub = ANY($1::text[])
`

func (q *Queries) ExpireTokensForUserSubs(ctx context.Context, dollar_1 []string) (int64, error) {
	result, err := q.db.ExecContext(ctx, expireTokensForUserSubs, pq.Array(dollar_1))
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listOfflineTokens = `-- name: ListOfflineTokens :many
SELECT user_sub, offline_token FROM user_offline_tokens
`

type ListOfflineTokensRow struct {
	UserSub      string
	OfflineToken []byte
}

func (q *Queries) ListOfflineTokens(ctx context.Context) ([]ListOfflineTokensRow, error) {
	rows, err := q.db.QueryContext(ctx, listOfflineTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOfflineTokensRow
	for rows.Next() {
		var i ListOfflineTokensRow
		if err := rows.Scan(&i.UserSub, &i.OfflineToken); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokensForUser = `-- name: ListTokensForUser :many
SELECT id, name, created_at FROM tokens WHERE user_sub = $1 ORDER BY created_at DESC
`

type ListTokensForUserRow struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

func (q *Queries) ListTokensForUser(ctx context.Context, userSub string) ([]ListTokensForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listTokensForUser, userSub)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTokensForUserRow
	for rows.Next() {
		var i ListTokensForUserRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewTokensForUser = `-- name: RenewTokensForUser :execrows
UPDATE tokens SET expires_at = NULL WHERE user_sub = $1
`

func (q *Queries) RenewTokensForUser(ctx context.Context, userSub string) (int64, error) {
	result, err := q.db.ExecContext(ctx, renewTokensForUser, userSub)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const tokenValidByHash = `-- name: TokenValidByHash :one
SELECT EXISTS(SELECT 1 FROM tokens WHERE token_hash = $1 AND (expires_at IS NULL OR expires_at > now()))
`

func (q *Queries) TokenValidByHash(ctx context.Context, tokenHash []byte) (bool, error) {
	row := q.db.QueryRowContext(ctx, tokenValidByHash, tokenHash)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateTokenName = `-- name: UpdateTokenName :execrows
UPDATE tokens SET name = $3 WHERE id = $1 AND user_sub = $2
`

type UpdateTokenNameParams struct {
	ID      uuid.UUID
	UserSub string
	Name    string
}

func (q *Queries) UpdateTokenName(ctx context.Context, arg UpdateTokenNameParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTokenName, arg.ID, arg.UserSub, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertContact = `-- name: UpsertContact :exec
INSERT INTO contacts (
    zoho_id, first_name, last_name, organization, email, phone, mobile,
    street, city, postal_code, status, modified_time, raw, synced_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
ON CONFLICT (zoho_id) DO UPDATE SET
    (first_name, last_name, organization, email, phone, mobile,
     street, city, postal_code, status, modified_time, raw, synced_at) =
    (EXCLUDED.first_name, EXCLUDED.last_name, EXCLUDED.organization,
     EXCLUDED.email, EXCLUDED.phone, EXCLUDED.mobile, EXCLUDED.street,
     EXCLUDED.city, EXCLUDED.postal_code, EXCLUDED.status,
     EXCLUDED.modified_time, EXCLUDED.raw, EXCLUDED.synced_at)
`

type UpsertContactParams struct {
	ZohoID       string
	FirstName    string
	LastName     string
	Organization string
	Email        string
	Phone        string
	Mobile       string
	Street       string
	City         string
	PostalCode   string
	Status       string
	ModifiedTime time.Time
	Raw          json.RawMessage
	SyncedAt     time.Time
}

func (q *Queries) UpsertContact(ctx context.Context, arg UpsertContactParams) error {
	_, err := q.db.ExecContext(ctx, upsertContact,
		arg.ZohoID,
		arg.FirstName,
		arg.LastName,
		arg.Organization,
		arg.Email,
		arg.Phone,
		arg.Mobile,
		arg.Street,
		arg.City,
		arg.PostalCode,
		arg.Status,
		arg.ModifiedTime,
		arg.Raw,
		arg.SyncedAt,
	)
	return err
}

const upsertOfflineToken = `-- name: UpsertOfflineToken :exec
INSERT INTO user_offline_tokens (user_sub, offline_token, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (user_sub) DO UPDATE SET
    offline_token = EXCLUDED.offline_token,
    updated_at    = EXCLUDED.updated_at
`

type UpsertOfflineTokenParams struct {
	UserSub      string
	OfflineToken []byte
}

func (q *Queries) UpsertOfflineToken(ctx context.Context, arg UpsertOfflineTokenParams) error {
	_, err := q.db.ExecContext(ctx, upsertOfflineToken, arg.UserSub, arg.OfflineToken)
	return err
}
