// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package database

import (
	"encoding/json"
	"time"
)

type Contact struct {
	ZohoID       string
	FirstName    string
	LastName     string
	Organization string
	Email        string
	Phone        string
	Mobile       string
	Street       string
	City         string
	PostalCode   string
	Status       string
	ModifiedTime time.Time
	Raw          json.RawMessage
}
