// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: queries.sql

package database

import (
	"context"
	"encoding/json"
	"time"
)

const allContacts = `-- name: AllContacts :many
SELECT zoho_id, first_name, last_name, organization, email, phone, mobile, street, city, postal_code, status, modified_time, raw, synced_at FROM contacts ORDER BY last_name, first_name
`

func (q *Queries) AllContacts(ctx context.Context) ([]Contact, error) {
	rows, err := q.db.QueryContext(ctx, allContacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ZohoID,
			&i.FirstName,
			&i.LastName,
			&i.Organization,
			&i.Email,
			&i.Phone,
			&i.Mobile,
			&i.Street,
			&i.City,
			&i.PostalCode,
			&i.Status,
			&i.ModifiedTime,
			&i.Raw,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteContactsSyncedBefore = `-- name: DeleteContactsSyncedBefore :execrows
DELETE FROM contacts WHERE synced_at < $1
`

func (q *Queries) DeleteContactsSyncedBefore(ctx context.Context, syncedAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteContactsSyncedBefore, syncedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertContact = `-- name: UpsertContact :exec
INSERT INTO contacts (
    zoho_id, first_name, last_name, organization, email, phone, mobile,
    street, city, postal_code, status, modified_time, raw, synced_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
ON CONFLICT (zoho_id) DO UPDATE SET
    (first_name, last_name, organization, email, phone, mobile,
     street, city, postal_code, status, modified_time, raw, synced_at) =
    (EXCLUDED.first_name, EXCLUDED.last_name, EXCLUDED.organization,
     EXCLUDED.email, EXCLUDED.phone, EXCLUDED.mobile, EXCLUDED.street,
     EXCLUDED.city, EXCLUDED.postal_code, EXCLUDED.status,
     EXCLUDED.modified_time, EXCLUDED.raw, EXCLUDED.synced_at)
`

type UpsertContactParams struct {
	ZohoID       string
	FirstName    string
	LastName     string
	Organization string
	Email        string
	Phone        string
	Mobile       string
	Street       string
	City         string
	PostalCode   string
	Status       string
	ModifiedTime time.Time
	Raw          json.RawMessage
	SyncedAt     time.Time
}

func (q *Queries) UpsertContact(ctx context.Context, arg UpsertContactParams) error {
	_, err := q.db.ExecContext(ctx, upsertContact,
		arg.ZohoID,
		arg.FirstName,
		arg.LastName,
		arg.Organization,
		arg.Email,
		arg.Phone,
		arg.Mobile,
		arg.Street,
		arg.City,
		arg.PostalCode,
		arg.Status,
		arg.ModifiedTime,
		arg.Raw,
		arg.SyncedAt,
	)
	return err
}
