FROM golang:1.27-alpine@sha256:cf6fca6641884b8433441b2b0652976f975e1d0fdd26d177eaaf8596087f3125

WORKDIR /app

RUN apk add git iputils bash bash-completion zsh fish nodejs npm

# Needed for Tailwind compile
RUN apk add libstdc++

RUN echo "source /etc/bash/bash_completion.sh" >> ~/.bash_profile
RUN echo "source <(bbook completion bash)" >> ~/.bashrc
RUN printf "%s\n" \
    "autoload -Uz compinit" \
    "compinit" \
    "source <(bbook completion zsh)" \
    >> ~/.zshrc

RUN mkdir -p ~/.config/fish
RUN echo "bbook completion fish 2>/dev/null | source" >> ~/.config/fish/config.fish


RUN go install github.com/air-verse/air@v1.64.5
RUN wget -qO- https://github.com/sqlc-dev/sqlc/releases/download/v1.31.0/sqlc_1.31.0_linux_amd64.tar.gz \
    | tar -xzC /usr/local/bin sqlc

COPY go.mod go.sum ./
RUN go mod download
