FROM golang:1.26-alpine

WORKDIR /app

RUN apk add git iputils bash bash-completion zsh fish

# Needed for Tailwind compile
RUN apk add libstdc++

RUN echo "source /etc/bash/bash_completion.sh" >> ~/.bash_profile
RUN echo "source <(bbook-backend completion bash)" >> ~/.bashrc
RUN printf "%s\n" \
    "autoload -Uz compinit" \
    "compinit" \
    "source <(bbook-backend completion zsh)" \
    >> ~/.zshrc

RUN mkdir -p ~/.config/fish
RUN echo "bbook-backend completion fish 2>/dev/null | source" >> ~/.config/fish/config.fish


RUN go install github.com/air-verse/air@v1.64.5
RUN wget -qO- https://github.com/sqlc-dev/sqlc/releases/download/v1.31.0/sqlc_1.31.0_linux_amd64.tar.gz \
    | tar -xzC /usr/local/bin sqlc
RUN wget -qO /usr/local/bin/tailwindcss https://github.com/tailwindlabs/tailwindcss/releases/download/v4.3.0/tailwindcss-linux-x64-musl \
    && chmod +x /usr/local/bin/tailwindcss

COPY go.mod go.sum ./
RUN go mod download
